"""empty message

Revision ID: 073af78756a5
Revises: 
Create Date: 2023-04-13 16:46:39.541727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '073af78756a5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('summary', sa.String(length=4096), nullable=True),
    sa.Column('address', sa.String(length=4096), nullable=True),
    sa.Column('league_id', sa.Integer(), nullable=True),
    sa.Column('create_user', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('img', sa.String(length=1000), nullable=True),
    sa.Column('create_user', sa.Integer(), nullable=True),
    sa.Column('is_prioity', sa.Integer(), nullable=True),
    sa.Column('is_compliance', sa.Integer(), nullable=True),
    sa.Column('is_meaning', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('landmark',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=2048), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('image', sa.String(length=4096), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('create_user', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('leagud',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('summary', sa.String(length=4096), nullable=True),
    sa.Column('image', sa.String(length=4096), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('server',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('img', sa.String(length=1000), nullable=True),
    sa.Column('create_user', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('server_collection',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('create_user', sa.Integer(), nullable=True),
    sa.Column('server_id', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=20), nullable=True),
    sa.Column('img', sa.String(length=2000), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.Column('role', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('server_collection')
    op.drop_table('server')
    op.drop_table('leagud')
    op.drop_table('landmark')
    op.drop_table('history')
    op.drop_table('activity')
    # ### end Alembic commands ###
