"""empty message

Revision ID: 346f7e43408f
Revises: a2bd28fd0246
Create Date: 2023-04-14 16:49:15.503546

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '346f7e43408f'
down_revision = 'a2bd28fd0246'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('league_cate',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('leagud', sa.Column('cate', sa.String(length=16), nullable=True))
    op.drop_column('leagud', 'type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leagud', sa.Column('type', mysql.VARCHAR(length=64), nullable=True))
    op.drop_column('leagud', 'cate')
    op.drop_table('league_cate')
    # ### end Alembic commands ###
