"""empty message

Revision ID: 6ea50d3f3edb
Revises: 9e3a0ae94538
Create Date: 2023-05-24 16:35:45.103398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ea50d3f3edb'
down_revision = '9e3a0ae94538'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=1000), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('url', sa.String(length=1000), nullable=True),
    sa.Column('type', sa.String(length=1000), nullable=True),
    sa.Column('params', sa.String(length=1000), nullable=True),
    sa.Column('flag', sa.String(length=1000), nullable=True),
    sa.Column('ip', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('log')
    # ### end Alembic commands ###
