"""empty message

Revision ID: a7199ffb50af
Revises: 346f7e43408f
Create Date: 2023-04-18 14:38:53.154353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7199ffb50af'
down_revision = '346f7e43408f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity', sa.Column('image', sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activity', 'image')
    # ### end Alembic commands ###
